version: "3.8"

services:

  time-api:

    build: ./time-api

  back-end:

    build: ./back-end

    depends_on:
      - time-api

  front-end:

    build: ./front-end
    
    depends_on:
      - back-end

  nginx:
    
    ports:
    - target: 80
      published: 80
      protocol: tcp  
    
    image: nginx:latest
    
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    
    depends_on:
      - front-end